// <auto-generated>
// This file was automatically generated by ECSReact Bridge System Generator
// Do not modify this file directly - it will be overwritten
// Generated from: ActionSelectionLoggingMiddleware
// System type: StandardMiddleware
// Generated at: 2025-09-02 00:09:58
// </auto-generated>

using Unity.Entities;
using Unity.Burst;
using Unity.Collections;
using ECSReact.Core;
using ECSReact.Samples.BattleSystem;

namespace ECSReact.Samples.BattleSystem
{
  /// <summary>
  /// Generated bridge for standard middleware: ActionSelectionLoggingMiddleware
  /// Provides zero-allocation iteration for middleware processing.
  /// </summary>
  [UpdateInGroup(typeof(MiddlewareSystemGroup))]
  [UpdateBefore(typeof(SimulationSystemGroup))]
  internal partial class ActionSelectionLoggingMiddleware_SelectActionTypeAction_Bridge : SystemBase
  {
    private ActionSelectionLoggingMiddleware userMiddleware;

    protected override void OnCreate()
    {
      base.OnCreate();
      RequireForUpdate<SelectActionTypeAction>();

      userMiddleware = World.GetOrCreateSystemManaged<ActionSelectionLoggingMiddleware>();
      if (userMiddleware.Enabled)
      {
        userMiddleware.Enabled = false;
      }
    }

    protected override void OnUpdate()
    {
      // Zero-allocation iteration
      foreach (var (action, entity) in
               SystemAPI.Query<RefRO<SelectActionTypeAction>>()
                 .WithAll<ActionTag>()
                 .WithEntityAccess())
      {
        userMiddleware.ProcessAction(action.ValueRO, entity);
      }
    }
  }
}
