// <auto-generated>
// This file was automatically generated by ECSReact Bridge System Generator
// Do not modify this file directly - it will be overwritten
// Generated from: DamageReducer
// System type: BurstReducer
// Generated at: 2025-09-03 23:04:11
// </auto-generated>

using Unity.Entities;
using Unity.Burst;
using Unity.Collections;
using ECSReact.Core;
using ECSReact.Samples.BattleSystem;

namespace ECSReact.Samples.BattleSystem
{
  /// <summary>
  /// Generated bridge for Burst-optimized reducer: DamageReducer
  /// Uses struct-based logic (DamageReducer.Logic) for maximum performance.
  /// Fully Burst-compiled with zero allocations and SIMD optimizations.
  /// </summary>
  [ReducerSystem]
  [BurstCompile]
  internal partial class DamageReducer_AttackAction_Bridge : SystemBase
  {
    // Static logic instance for zero allocations
    private static readonly DamageReducer.Logic logic
      = default(DamageReducer.Logic);

    protected override void OnCreate()
    {
      base.OnCreate();
      RequireForUpdate<PartyState>();
      RequireForUpdate<AttackAction>();
    }

    [BurstCompile]
    protected override void OnUpdate()
    {
      var state = SystemAPI.GetSingletonRW<PartyState>();

      foreach (var action in
        SystemAPI.Query<RefRO<AttackAction>>()
          .WithAll<ActionTag>())
      {
        logic.Execute(ref state.ValueRW, action.ValueRO);
      }
    }
  }
}
