// <auto-generated>
// This file was automatically generated by ECSReact Bridge System Generator
// Do not modify this file directly - it will be overwritten
// Generated from: TurnChangeLoggingMiddleware
// System type: StandardMiddleware
// Generated at: 2025-09-03 12:03:19
// </auto-generated>

using Unity.Entities;
using Unity.Burst;
using Unity.Collections;
using ECSReact.Core;
using ECSReact.Samples.BattleSystem;

namespace ECSReact.Samples.BattleSystem
{
  /// <summary>
  /// Generated bridge for standard middleware: TurnChangeLoggingMiddleware
  /// Provides zero-allocation iteration for middleware processing.
  /// </summary>
  [UpdateInGroup(typeof(MiddlewareSystemGroup))]
  [UpdateBefore(typeof(SimulationSystemGroup))]
  internal partial class TurnChangeLoggingMiddleware_NextTurnAction_Bridge : SystemBase
  {
    private TurnChangeLoggingMiddleware middleware;

    protected override void OnCreate()
    {
      base.OnCreate();
      RequireForUpdate<NextTurnAction>();

      middleware = World.GetOrCreateSystemManaged<TurnChangeLoggingMiddleware>();
      if (middleware.Enabled)
      {
        middleware.Enabled = false;
      }
    }

    protected override void OnUpdate()
    {
      // Zero-allocation iteration
      foreach (var (action, entity) in
        SystemAPI.Query<RefRO<NextTurnAction>>()
          .WithAll<ActionTag>()
          .WithEntityAccess())
      {
        middleware.ProcessAction(action.ValueRO, entity);
      }
    }
  }
}
