// <auto-generated>
// This file was automatically generated by StateSubscriptionHelper Generator
// Namespace: ECSReact.Samples.SimpleSetup.Namespace1.State
// Do not modify this file directly - it will be overwritten
// </auto-generated>

using System;
using ECSReact.Core;
using ECSReact.Samples.SimpleSetup.Namespace1.State;

namespace ECSReact.Samples.SimpleSetup.Namespace1.State
{
  /// <summary>
  /// Generated helpers for StateSubscriptionHelper that register subscription handlers for ECSReact.Samples.SimpleSetup.Namespace1.State state types.
  /// </summary>
  public static class StateSubscriptionRegistration
  {
    /// <summary>
    /// Initialize subscription handlers for ECSReact.Samples.SimpleSetup.Namespace1.State state types.
    /// Call this method during application startup or when setting up the UI system.
    /// </summary>
    public static void InitializeSubscriptions()
    {
      // Register handlers for StateNamespace1
      StateSubscriptionHelper.RegisterStateSubscriptionHandlers<StateNamespace1>(
        subscriber => StateNotificationEvents.OnStateNamespace1Changed += subscriber.OnStateChanged,
        subscriber => StateNotificationEvents.OnStateNamespace1Changed -= subscriber.OnStateChanged
      );

    }
  }
}
