// <auto-generated>
// This file was automatically generated by UIStateNotifier Generator
// Namespace: ECSReact.Samples.SimpleSetup.Namespace1.State
// Do not modify this file directly - it will be overwritten
// </auto-generated>

using System;
using ECSReact.Core;
using ECSReact.Samples.SimpleSetup.Namespace1.State;

namespace ECSReact.Samples.SimpleSetup.Namespace1.State
{
  /// <summary>
  /// Generated extensions for UIStateNotifier that provide typed events for ECSReact.Samples.SimpleSetup.Namespace1.State state types.
  /// </summary>
  public static class StateNotificationEvents
  {
    /// <summary>
    /// Event fired when StateNamespace1 changes.
    /// </summary>
    public static System.Action<StateNamespace1> OnStateNamespace1Changed;

    /// <summary>
    /// Initialize event processors for ECSReact.Samples.SimpleSetup.Namespace1.State state types.
    /// Call this method during application startup or when setting up the UI system.
    /// </summary>
    public static void InitializeEvents()
    {
      ECSReact.Core.UIStateNotifier
        .RegisterEventProcessor<ECSReact.Samples.SimpleSetup.Namespace1.State.StateNamespace1ChangedEvent>(evt => 
          OnStateNamespace1Changed?.Invoke(evt.newState));
    }
  }
}
