// <auto-generated>
// This file was automatically generated by StateRegistryGenerator
// Namespace: ECSReact.Samples.SimpleSetup.Namespace1.State
// Generated on: 11/11/2025 12:18:52 a.m.
// Do not modify this file manually - your changes will be overwritten
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using Unity.Entities;
using Unity.Collections;
using UnityEngine;
using ECSReact.Core;
using ECSReact.Samples.SimpleSetup.Namespace1.State;

namespace ECSReact.Samples.SimpleSetup.Namespace1.State
{
  /// <summary>
  /// Auto-generated state registry for ECSReact.Samples.SimpleSetup.Namespace1.State namespace.
  /// Provides strongly-typed access to all game states in this namespace.
  /// </summary>
  public class ECSReactSamplesSimpleSetupNamespace1StateStateRegistry : IStateRegistry
  {
    private static ECSReactSamplesSimpleSetupNamespace1StateStateRegistry _instance;
    private static readonly object _lock = new object();

    /// <summary>
    /// Singleton instance of the registry.
    /// </summary>
    public static ECSReactSamplesSimpleSetupNamespace1StateStateRegistry Instance {
      get {
        if (_instance == null) {
          lock (_lock) {
            if (_instance == null) {
              _instance = new ECSReactSamplesSimpleSetupNamespace1StateStateRegistry();
              _instance.Initialize();
            }
          }
        }
        return _instance;
      }
    }

    private readonly Dictionary<Type, IStateInfo> stateInfos = new Dictionary<Type, IStateInfo>();

    private void Initialize()
    {
      stateInfos.Add(typeof(StateNamespace1), new StateInfoBase
      {
        Type = typeof(StateNamespace1),
        Name = "StateNamespace1",
        Namespace = "ECSReact.Samples.SimpleSetup.Namespace1.State",
        CreateSingletonFunc = (em, name) => em.CreateSingleton(default(StateNamespace1), name),
        GetComponentFunc = (em, entity) => em.GetComponentData<StateNamespace1>(entity),
        SetComponentAction = (em, entity, data) => em.SetComponentData(entity, (StateNamespace1)data),
        DeserializeJsonFunc = (json) => string.IsNullOrEmpty(json) ? default(StateNamespace1) : JsonUtility.FromJson<StateNamespace1>(json)
      });
    }

    public IReadOnlyDictionary<Type, IStateInfo> AllStates => stateInfos;

    public IStateInfo GetStateInfo(Type type)
    {
      return stateInfos.TryGetValue(type, out var info) ? info : null;
    }

    public Entity CreateStateSingleton(EntityManager entityManager, Type stateType, FixedString64Bytes name)
    {
      var info = GetStateInfo(stateType);
      return info?.CreateSingleton(entityManager, name) ?? Entity.Null;
    }

    public List<Type> GetStatesByNamespace(string namespaceName)
    {
      return stateInfos.Values
        .Where(info => info.Namespace == namespaceName)
        .Select(info => info.Type)
        .ToList();
    }

    public List<string> GetAllNamespaces()
    {
      return stateInfos.Values
        .Select(info => info.Namespace)
        .Distinct()
        .OrderBy(ns => ns)
        .ToList();
    }

    /// <summary>
    /// Ensures the registry is created and registered with StateRegistryService.
    /// Called automatically by Unity's RuntimeInitializeOnLoadMethod.
    /// </summary>
    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterAssembliesLoaded)]
    public static void EnsureRegistered()
    {
      var registry = Instance;
      StateRegistryService.RegisterRegistry(registry);
    }
  }
}
