// <auto-generated>
// This file was automatically generated by StateSubscriptionHelper Generator
// Namespace: ECSReact.Samples.SimpleSetup.Namespace1.State
// Do not modify this file directly - it will be overwritten
// </auto-generated>

using Unity.Entities;
using Unity.Burst;
using ECSReact.Core;
using ECSReact.Samples.SimpleSetup.Namespace1.State;

namespace ECSReact.Samples.SimpleSetup.Namespace1.State
{
  /// <summary>
  /// Generated system that detects StateNamespace1 changes and queues UI events.
  /// Generated for namespace: ECSReact.Samples.SimpleSetup.Namespace1.State
  /// </summary>
  [BurstCompile]
  [UINotificationSystem]
  public partial class StateNamespace1ChangeNotificationSystem : StateChangeNotificationSystem<StateNamespace1>
  {
    protected override UIEvent CreateStateChangeEvent(StateNamespace1 newState, StateNamespace1 oldState, bool hasOldState)
    {
      return new StateNamespace1ChangedEvent(newState, oldState, hasOldState);
    }
  }

}
