// <auto-generated>
// This file was automatically generated by UIStateNotifier Generator
// Namespace: ECSReact.Samples.SimpleSetup.Namespace1.State
// Do not modify this file directly - it will be overwritten
// </auto-generated>

using ECSReact.Core;
using ECSReact.Samples.SimpleSetup.Namespace1.State;

namespace ECSReact.Samples.SimpleSetup.Namespace1.State
{
  /// <summary>
  /// UI event fired when StateNamespace1 from ECSReact.Samples.SimpleSetup.Namespace1.State changes.
  /// </summary>
  public class StateNamespace1ChangedEvent : UIEvent
  {
    public StateNamespace1 newState;
    public StateNamespace1 oldState;
    public bool hasOldState;

    public StateNamespace1ChangedEvent(StateNamespace1 newState, StateNamespace1 oldState, bool hasOldState)
    {
      this.newState = newState;
      this.oldState = oldState;
      this.hasOldState = hasOldState;
      this.priority = UIEventPriority.Normal;
    }
  }
}
