// <auto-generated>
// This file was automatically generated by ECSReact Bridge System Generator
// Do not modify this file directly - it will be overwritten
// Generated from: AddCharacterReducer
// System type: StandardReducer
// Generated at: 2025-09-03 12:03:19
// </auto-generated>

using Unity.Entities;
using Unity.Burst;
using Unity.Collections;
using ECSReact.Core;
using ECSReact.Samples.BattleSystem;

namespace ECSReact.Samples.BattleSystem
{
  /// <summary>
  /// Generated bridge for standard reducer: AddCharacterReducer
  /// Provides zero-allocation iteration using SystemAPI.Query.
  /// </summary>
  [UpdateInGroup(typeof(ReducerSystemGroup))]
  internal partial class AddCharacterReducer_AddCharacterAction_Bridge : SystemBase
  {
    private AddCharacterReducer reducer;

    protected override void OnCreate()
    {
      base.OnCreate();
      RequireForUpdate<PartyState>();
      RequireForUpdate<AddCharacterAction>();

      reducer = World.GetOrCreateSystemManaged<AddCharacterReducer>();
      if (reducer.Enabled)
      {
        reducer.Enabled = false;
      }
    }

    protected override void OnUpdate()
    {
      var state = SystemAPI.GetSingletonRW<PartyState>();

      // Zero-allocation iteration
      foreach (var action in
        SystemAPI.Query<RefRO<AddCharacterAction>>()
          .WithAll<ActionTag>())
      {
        reducer.ReduceState(ref state.ValueRW, action.ValueRO);
      }
    }
  }
}
