// <auto-generated>
// This file was automatically generated by ECSReact Bridge System Generator
// Do not modify this file directly - it will be overwritten
// Generated from: BattleLogReducer
// System type: StandardReducer
// Generated at: 2025-09-03 12:43:44
// </auto-generated>

using Unity.Entities;
using Unity.Burst;
using Unity.Collections;
using ECSReact.Core;
using ECSReact.Samples.BattleSystem;

namespace ECSReact.Samples.BattleSystem
{
  /// <summary>
  /// Generated bridge for standard reducer: BattleLogReducer
  /// Provides zero-allocation iteration using SystemAPI.Query.
  /// </summary>
  [ReducerSystem]
  internal partial class BattleLogReducer_BattleLogAction_Bridge : SystemBase
  {
    private BattleLogReducer reducer;

    protected override void OnCreate()
    {
      base.OnCreate();
      RequireForUpdate<BattleLogState>();
      RequireForUpdate<BattleLogAction>();

      reducer = World.GetOrCreateSystemManaged<BattleLogReducer>();
      if (reducer.Enabled)
      {
        reducer.Enabled = false;
      }
    }

    protected override void OnUpdate()
    {
      var state = SystemAPI.GetSingletonRW<BattleLogState>();

      // Zero-allocation iteration
      foreach (var action in
        SystemAPI.Query<RefRO<BattleLogAction>>()
          .WithAll<ActionTag>())
      {
        reducer.ReduceState(ref state.ValueRW, action.ValueRO);
      }
    }
  }
}
