// <auto-generated>
// This file was automatically generated by ECSReact Bridge System Generator
// Do not modify this file directly - it will be overwritten
// Generated from: ClearBattleLogReducer
// System type: StandardReducer
// Generated at: 2025-09-03 23:04:11
// </auto-generated>

using Unity.Entities;
using Unity.Burst;
using Unity.Collections;
using ECSReact.Core;
using ECSReact.Samples.BattleSystem;

namespace ECSReact.Samples.BattleSystem
{
  /// <summary>
  /// Generated bridge for standard reducer: ClearBattleLogReducer
  /// Provides zero-allocation iteration using SystemAPI.Query.
  /// </summary>
  [ReducerSystem]
  internal partial class ClearBattleLogReducer_ClearBattleLogAction_Bridge : SystemBase
  {
    private ClearBattleLogReducer reducer;

    protected override void OnCreate()
    {
      base.OnCreate();
      RequireForUpdate<BattleLogState>();
      RequireForUpdate<ClearBattleLogAction>();

      reducer = World.GetOrCreateSystemManaged<ClearBattleLogReducer>();
      if (reducer.Enabled)
      {
        reducer.Enabled = false;
      }
    }

    protected override void OnUpdate()
    {
      var state = SystemAPI.GetSingletonRW<BattleLogState>();

      // Zero-allocation iteration
      foreach (var action in
        SystemAPI.Query<RefRO<ClearBattleLogAction>>()
          .WithAll<ActionTag>())
      {
        reducer.ReduceState(ref state.ValueRW, action.ValueRO);
      }
    }
  }
}
