// <auto-generated>
// This file was automatically generated by ECSReact Bridge System Generator
// Do not modify this file directly - it will be overwritten
// Generated from: DamageReducer
// System type: StandardReducer
// Generated at: 2025-09-03 12:43:44
// </auto-generated>

using Unity.Entities;
using Unity.Burst;
using Unity.Collections;
using ECSReact.Core;
using ECSReact.Samples.BattleSystem;

namespace ECSReact.Samples.BattleSystem
{
  /// <summary>
  /// Generated bridge for standard reducer: DamageReducer
  /// Provides zero-allocation iteration using SystemAPI.Query.
  /// </summary>
  [ReducerSystem]
  internal partial class DamageReducer_AttackAction_Bridge : SystemBase
  {
    private DamageReducer reducer;

    protected override void OnCreate()
    {
      base.OnCreate();
      RequireForUpdate<PartyState>();
      RequireForUpdate<AttackAction>();

      reducer = World.GetOrCreateSystemManaged<DamageReducer>();
      if (reducer.Enabled)
      {
        reducer.Enabled = false;
      }
    }

    protected override void OnUpdate()
    {
      var state = SystemAPI.GetSingletonRW<PartyState>();

      // Zero-allocation iteration
      foreach (var action in
        SystemAPI.Query<RefRO<AttackAction>>()
          .WithAll<ActionTag>())
      {
        reducer.ReduceState(ref state.ValueRW, action.ValueRO);
      }
    }
  }
}
