// <auto-generated>
// This file was automatically generated by ECSReact Bridge System Generator
// Do not modify this file directly - it will be overwritten
// Generated from: UIActionSelectionReducer
// System type: StandardReducer
// Generated at: 2025-09-03 11:00:47
// </auto-generated>

using Unity.Entities;
using Unity.Burst;
using Unity.Collections;
using ECSReact.Core;
using ECSReact.Samples.BattleSystem;

namespace ECSReact.Samples.BattleSystem
{
  /// <summary>
  /// Generated bridge for standard reducer: UIActionSelectionReducer
  /// Provides zero-allocation iteration using SystemAPI.Query.
  /// </summary>
  [UpdateInGroup(typeof(ReducerSystemGroup))]
  internal partial class UIActionSelectionReducer_SelectActionTypeAction_Bridge : SystemBase
  {
    private UIActionSelectionReducer reducer;

    protected override void OnCreate()
    {
      base.OnCreate();
      RequireForUpdate<UIBattleState>();
      RequireForUpdate<SelectActionTypeAction>();

      reducer = World.GetOrCreateSystemManaged<UIActionSelectionReducer>();
      if (reducer.Enabled)
      {
        reducer.Enabled = false;
      }
    }

    protected override void OnUpdate()
    {
      var state = SystemAPI.GetSingletonRW<UIBattleState>();

      // Zero-allocation iteration
      foreach (var (action, entity) in
               SystemAPI.Query<RefRO<SelectActionTypeAction>>()
                 .WithAll<ActionTag>()
                 .WithEntityAccess())
      {
        reducer.ReduceState(ref state.ValueRW, action.ValueRO);
      }
    }
  }
}
