// <auto-generated>
// This file was automatically generated by ECSReact Bridge System Generator
// Do not modify this file directly - it will be overwritten
// Generated from: UICancelActionReducer
// System type: StandardReducer
// Generated at: 2025-09-02 00:09:58
// </auto-generated>

using Unity.Entities;
using Unity.Burst;
using Unity.Collections;
using ECSReact.Core;
using ECSReact.Samples.BattleSystem;

namespace ECSReact.Samples.BattleSystem
{
  /// <summary>
  /// Generated bridge for standard reducer: UICancelActionReducer
  /// Provides zero-allocation iteration using SystemAPI.Query.
  /// </summary>
  [UpdateInGroup(typeof(ReducerSystemGroup))]
  internal partial class UICancelActionReducer_CancelActionAction_Bridge : SystemBase
  {
    private UICancelActionReducer userReducer;

    protected override void OnCreate()
    {
      base.OnCreate();
      RequireForUpdate<UIBattleState>();
      RequireForUpdate<CancelActionAction>();

      userReducer = World.GetOrCreateSystemManaged<UICancelActionReducer>();
      if (userReducer.Enabled)
      {
        userReducer.Enabled = false;
      }
    }

    protected override void OnUpdate()
    {
      var state = SystemAPI.GetSingletonRW<UIBattleState>();

      // Zero-allocation iteration
      foreach (var (action, entity) in
               SystemAPI.Query<RefRO<CancelActionAction>>()
                 .WithAll<ActionTag>()
                 .WithEntityAccess())
      {
        userReducer.ReduceState(ref state.ValueRW, action.ValueRO);
      }
    }
  }
}
