// <auto-generated>
// This file was automatically generated by StateSubscriptionHelper Generator
// Namespace: ECSReact.Samples.SimpleSetup.Namespace2.State
// Do not modify this file directly - it will be overwritten
// </auto-generated>

using System;
using ECSReact.Core;
using ECSReact.Samples.SimpleSetup.Namespace2.State;

namespace ECSReact.Samples.SimpleSetup.Namespace2.State
{
  /// <summary>
  /// Generated helpers for StateSubscriptionHelper that register subscription handlers for ECSReact.Samples.SimpleSetup.Namespace2.State state types.
  /// </summary>
  public static class StateSubscriptionRegistration
  {
    /// <summary>
    /// Initialize subscription handlers for ECSReact.Samples.SimpleSetup.Namespace2.State state types.
    /// Call this method during application startup or when setting up the UI system.
    /// </summary>
    public static void InitializeSubscriptions()
    {
      // Register handlers for StateNamespace2
      StateSubscriptionHelper.RegisterStateSubscriptionHandlers<StateNamespace2>(
        subscriber => StateNotificationEvents.OnStateNamespace2Changed += subscriber.OnStateChanged,
        subscriber => StateNotificationEvents.OnStateNamespace2Changed -= subscriber.OnStateChanged
      );

    }
  }
}
