// <auto-generated>
// This file was automatically generated by StateSubscriptionHelper Generator
// Namespace: ECSReact.Samples.SimpleSetup.Namespace2.State
// Do not modify this file directly - it will be overwritten
// </auto-generated>

using Unity.Entities;
using Unity.Burst;
using ECSReact.Core;
using ECSReact.Samples.SimpleSetup.Namespace2.State;

namespace ECSReact.Samples.SimpleSetup.Namespace2.State
{
  /// <summary>
  /// Generated system that detects StateNamespace2 changes and queues UI events.
  /// Generated for namespace: ECSReact.Samples.SimpleSetup.Namespace2.State
  /// </summary>
  [BurstCompile]
  [UINotificationSystem]
  public partial class StateNamespace2ChangeNotificationSystem : StateChangeNotificationSystem<StateNamespace2>
  {
    protected override UIEvent CreateStateChangeEvent(StateNamespace2 newState, StateNamespace2 oldState, bool hasOldState)
    {
      return new StateNamespace2ChangedEvent(newState, oldState, hasOldState);
    }
  }

}
