// <auto-generated>
// This file was automatically generated by UIStateNotifier Generator
// Namespace: ECSReact.Samples.BattleSystem
// Do not modify this file directly - it will be overwritten
// </auto-generated>

using ECSReact.Core;
using ECSReact.Samples.BattleSystem;

namespace ECSReact.Samples.BattleSystem
{
  /// <summary>
  /// UI event fired when AIThinkingState from ECSReact.Samples.BattleSystem changes.
  /// </summary>
  public class AIThinkingStateChangedEvent : UIEvent
  {
    public AIThinkingState newState;
    public AIThinkingState oldState;
    public bool hasOldState;

    public AIThinkingStateChangedEvent(AIThinkingState newState, AIThinkingState oldState, bool hasOldState)
    {
      this.newState = newState;
      this.oldState = oldState;
      this.hasOldState = hasOldState;
      this.priority = UIEventPriority.Normal;
    }
  }

  /// <summary>
  /// UI event fired when BattleLogState from ECSReact.Samples.BattleSystem changes.
  /// </summary>
  public class BattleLogStateChangedEvent : UIEvent
  {
    public BattleLogState newState;
    public BattleLogState oldState;
    public bool hasOldState;

    public BattleLogStateChangedEvent(BattleLogState newState, BattleLogState oldState, bool hasOldState)
    {
      this.newState = newState;
      this.oldState = oldState;
      this.hasOldState = hasOldState;
      this.priority = UIEventPriority.Normal;
    }
  }

  /// <summary>
  /// UI event fired when BattleState from ECSReact.Samples.BattleSystem changes.
  /// </summary>
  public class BattleStateChangedEvent : UIEvent
  {
    public BattleState newState;
    public BattleState oldState;
    public bool hasOldState;

    public BattleStateChangedEvent(BattleState newState, BattleState oldState, bool hasOldState)
    {
      this.newState = newState;
      this.oldState = oldState;
      this.hasOldState = hasOldState;
      this.priority = UIEventPriority.Normal;
    }
  }

  /// <summary>
  /// UI event fired when CharacterHealthState from ECSReact.Samples.BattleSystem changes.
  /// </summary>
  public class CharacterHealthStateChangedEvent : UIEvent
  {
    public CharacterHealthState newState;
    public CharacterHealthState oldState;
    public bool hasOldState;

    public CharacterHealthStateChangedEvent(CharacterHealthState newState, CharacterHealthState oldState, bool hasOldState)
    {
      this.newState = newState;
      this.oldState = oldState;
      this.hasOldState = hasOldState;
      this.priority = UIEventPriority.Normal;
    }
  }

  /// <summary>
  /// UI event fired when CharacterManaState from ECSReact.Samples.BattleSystem changes.
  /// </summary>
  public class CharacterManaStateChangedEvent : UIEvent
  {
    public CharacterManaState newState;
    public CharacterManaState oldState;
    public bool hasOldState;

    public CharacterManaStateChangedEvent(CharacterManaState newState, CharacterManaState oldState, bool hasOldState)
    {
      this.newState = newState;
      this.oldState = oldState;
      this.hasOldState = hasOldState;
      this.priority = UIEventPriority.Normal;
    }
  }

  /// <summary>
  /// UI event fired when CharacterStatusState from ECSReact.Samples.BattleSystem changes.
  /// </summary>
  public class CharacterStatusStateChangedEvent : UIEvent
  {
    public CharacterStatusState newState;
    public CharacterStatusState oldState;
    public bool hasOldState;

    public CharacterStatusStateChangedEvent(CharacterStatusState newState, CharacterStatusState oldState, bool hasOldState)
    {
      this.newState = newState;
      this.oldState = oldState;
      this.hasOldState = hasOldState;
      this.priority = UIEventPriority.Normal;
    }
  }

  /// <summary>
  /// UI event fired when CharacterIdentityState from ECSReact.Samples.BattleSystem changes.
  /// </summary>
  public class CharacterIdentityStateChangedEvent : UIEvent
  {
    public CharacterIdentityState newState;
    public CharacterIdentityState oldState;
    public bool hasOldState;

    public CharacterIdentityStateChangedEvent(CharacterIdentityState newState, CharacterIdentityState oldState, bool hasOldState)
    {
      this.newState = newState;
      this.oldState = oldState;
      this.hasOldState = hasOldState;
      this.priority = UIEventPriority.Normal;
    }
  }

  /// <summary>
  /// UI event fired when CharacterRosterState from ECSReact.Samples.BattleSystem changes.
  /// </summary>
  public class CharacterRosterStateChangedEvent : UIEvent
  {
    public CharacterRosterState newState;
    public CharacterRosterState oldState;
    public bool hasOldState;

    public CharacterRosterStateChangedEvent(CharacterRosterState newState, CharacterRosterState oldState, bool hasOldState)
    {
      this.newState = newState;
      this.oldState = oldState;
      this.hasOldState = hasOldState;
      this.priority = UIEventPriority.Normal;
    }
  }

  /// <summary>
  /// UI event fired when SaveState from ECSReact.Samples.BattleSystem changes.
  /// </summary>
  public class SaveStateChangedEvent : UIEvent
  {
    public SaveState newState;
    public SaveState oldState;
    public bool hasOldState;

    public SaveStateChangedEvent(SaveState newState, SaveState oldState, bool hasOldState)
    {
      this.newState = newState;
      this.oldState = oldState;
      this.hasOldState = hasOldState;
      this.priority = UIEventPriority.Normal;
    }
  }

  /// <summary>
  /// UI event fired when UIBattleState from ECSReact.Samples.BattleSystem changes.
  /// </summary>
  public class UIBattleStateChangedEvent : UIEvent
  {
    public UIBattleState newState;
    public UIBattleState oldState;
    public bool hasOldState;

    public UIBattleStateChangedEvent(UIBattleState newState, UIBattleState oldState, bool hasOldState)
    {
      this.newState = newState;
      this.oldState = oldState;
      this.hasOldState = hasOldState;
      this.priority = UIEventPriority.Normal;
    }
  }
}
