// <auto-generated>
// This file was automatically generated by UIStateNotifier Generator
// Namespace: ECSReact.Samples.SimpleSetup.Namespace2.State
// Do not modify this file directly - it will be overwritten
// </auto-generated>

using ECSReact.Core;
using ECSReact.Samples.SimpleSetup.Namespace2.State;

namespace ECSReact.Samples.SimpleSetup.Namespace2.State
{
  /// <summary>
  /// UI event fired when StateNamespace2 from ECSReact.Samples.SimpleSetup.Namespace2.State changes.
  /// </summary>
  public class StateNamespace2ChangedEvent : UIEvent
  {
    public StateNamespace2 newState;
    public StateNamespace2 oldState;
    public bool hasOldState;

    public StateNamespace2ChangedEvent(StateNamespace2 newState, StateNamespace2 oldState, bool hasOldState)
    {
      this.newState = newState;
      this.oldState = oldState;
      this.hasOldState = hasOldState;
      this.priority = UIEventPriority.Normal;
    }
  }
}
